name: Testing

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: TrueBrain/actions-flake8@master
      with:
        path: dorpsgek

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build .
